#+TITLE:   Armagedon Config
#+DATE:    October 25, 2020
#+STARTUP: inlineimages nofold
#+PROPERTY: header-args :tangle config.el

* MY DOOM EMACS CONFIG 
** PERSONAL DETAILS
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets.

#+BEGIN_SRC emacs-lisp
(setq user-full-name "Urban Avsec"
      user-mail-address "urban.avsec@outlook.com")
#+END_SRC


** DOOM THEME
 Doom exposes five (optional) variables for controlling fonts in Doom. Here
 are the three important ones:
 + `doom-font'
 + `doom-variable-pitch-font'
 + `doom-big-font' -- used for `doom-big-font-mode'; use this for presentations or streaming.
   
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-dracula)
#+END_SRC


** SANE CURSOR MOVEMENT
To enalbe to move in visual lines using `j` and `k` and not skip lines. 
#+BEGIN_SRC emacs-lisp
(after! evil
  (map! :n "j" 'evil-next-visual-line
        :n "k" 'evil-previous-visual-line))
#+END_SRC


** ORG MODE
Org Mode Configurations

Make my default =org-directory= equal to the /Brain/ folder in my cloud for cross device support. This must eval before /org/ loads. 
#+BEGIN_SRC emacs-lisp
(setq org-directory "~/pCloud Drive/Crypto Folder/Brain")
#+END_SRC

The title in my config should be 40% slightly larger and inline images should always load. 
#+BEGIN_SRC emacs-lisp
(after! org
  (setq org-startup-with-inline-images t)
  (custom-set-faces!
    '(org-document-title :height 1.4)))
#+END_SRC

Set =org-agenda-files= variable to my /Tasks/ folder inside the /Brain/ folder, where all my Org pages with TODO's might exist. Also add new types of TODO states:
+ =MEETING= A scheduled meeting
+ =BLOCKED= An external block
#+BEGIN_SRC emacs-lisp
(after! org
  (setq org-agenda-files '("~/pCloud Drive/Crypto Folder/Brain/Tasks"))
  (setq org-todo-keywords '((sequence "TODO(t)" "PROJ(p)" "MEETING(m)" "BLOCKED(b)" "LEARN(l)" "DOING" "|" "DONE(d)" "CANCELLED(c)")))
  )
#+END_SRC

#+RESULTS:
| sequence | TODO(t) | PROJ(p) | MEETING(m) | BLOCKED(b) | LEARN(l) | DOING |   |   | DONE(d) | CANCELLED(c) |


*** ORG ROAM
=Org Roam= is used to control my digital brain. The brain is located in my Crypto Folder, but the DB lives outside to allow sharing of the documents accross multiple devices. When switching =org-roam-build-cache= should be called to regenreate the Database.

#+BEGIN_SRC emacs-lisp
(setq org-roam-directory "~/pCloud Drive/Crypto Folder/Brain")
(setq org-roam-db-locaiton "~/org-roam.db")
(setq org-roam-tag-sources '(prop first-directory))
#+END_SRC

**** Roam Templates
There are 3 Core Templates in my Roam:
+ =Task= Any Document living in the /Task/ directory, which is also tracked by =org-agenda=. TODO's , Projects, Meetings, etc. should go into this folder. 
+ =Wiki= The general Wiki Type Knowledge System. Files live under /Wiki/ directory. Any atoms of knowledge with their source can go in there. 
+ =Zettel= The classical implementation of /Zettelkaste/ method. The documents live under the /Zettel/ directory. This documents should represent pure zettels. That is pieces of my thinking and other people opinions with correct sources. 
  
#+BEGIN_SRC emacs-lisp
(after! org
  (setq org-roam-capture-templates
        '(("T" "Task" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "Tasks/%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d %H:%M:%S>\n"
           :unnarrowed t)
          ("W" "Wiki" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "Wiki/%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d %H:%M:%S>\n#+STARTUP: latexpreview showall"
           :unnarrowed t)
          ("Z" "Zettel" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "Zettel/%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d %H:%M:%S>\n#+STARTUP: latexpreview showall"
           :unnarrowed t)
          ("L" "Literature" plain (function org-roam--capture-get-point)
           "%?"
           :file-name "LiteratureNote/%<%Y%m%d%H%M%S>-${slug}"
           :head "#+TITLE: ${title}\n#+CREATED: %<%Y-%m-%d %H:%M:%S>\n#+STARTUP: latexpreview showall"
           :unnarrowed t))))
#+END_SRC

** LANG
*** RUST
Enables Rust over TRAMP
#+BEGIN_SRC emacs-lisp
(after! lsp-mode
  (lsp-register-client
   (make-lsp-client :new-connection (lsp-tramp-connection "rust-analyzer")
                    :major-modes '(rust-mode rustic-mode)
                    :priority 1
                    :initialization-options 'lsp-rust-analyzer--make-init-options
                    :notification-handlers (ht<-alist lsp-rust-notification-handlers) //TODO Unknwon Constant
                    :action-handlers (ht ("rust-analyzer.runSingle" #'lsp-rust--analyzer-run-single))
                    :library-folders-fn(lambda (_workplace) lsp-rust-library-directions)
                    :after-open-fn (lambda ()
                                     (when lsp-rust-analyzer-server-display-hints
                                       (lsp-rust-analyzer-inlay-hints-mode)))
                    :ignore-messages nil
                    :remote? t
                    :custom-capabilities `((experimental . ((snippetTextEdit . ,lsp-enable-snipet ))))
                    :server-id 'rust-analyzer-remote)))
#+END_SRC


** TEMP
#+BEGIN_SRC emacs-lisp
;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)


;; Here are some additional functions/macros that could help you configure Doom:
;;
;; - `load!' for loading external *.el files relative to this one
;; - `use-package!' for configuring packages
;; - `after!' for running code after a package has loaded
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.

;; Org - Attach Settings
(setq org-attach-id-dir "~/pCloud Drive/Crypto Folder/Brain/Attachments")

(use-package org-download
  :after org
  :defer nil
  :custom
  (org-download-method 'directory)
  (org-download-imge-dir "~/pCloud Drive/Crypto Fodler/Brain/Attachments")
  (org-download-screenshot-method "fireshot gui --raw > %s")
  :config
  (require 'org-download))

;; Org Agenda Configs
;;
;; Org Agenda is used to track my items that needs to happen


;; Org Roam Bibtex Settings
(use-package org-roam-bibtex
  :after org-roam
  :hook (org-roam-mode . org-roam-bibtex-mode)
  )

;; Org Roam Server
(use-package org-roam-server
  :after org-roam
  :config
  (setq org-roam-server-host "127.0.0.1"
        org-roam-server-port 8080
        org-roam-server-export-inline-images t
        org-roam-server-authenticate nil
        org-roam-server-export-inline-images t
        org-roam-server-serve-files nil
        org-roam-server-served-file-extensions '("pdf" "mp4" "ogv")
        org-roam-server-network-poll t
        org-roam-server-network-arrows nil
        org-roam-server-network-truncate t
        org-roam-server-network-label-truncate-length 60
        org-roam-server-network-label-wrap-length 20)
  (defun org-roam-server-open ()
    "Ensure the server is active, then open the roam graph."
    (interactive)
    (org-roam-server-mode 1)
    (browse-url-xdg-open (format "http://localhost:%d" org-roam-server-port))))


;; Org - Noter Configs
(setq org-noter-notes-search-path '("~/pCloud Drive/Crypto Folder/Library"))

;; Org - Ref Configs
(setq reftex-default-bibliography '("~/pCloud Drive/Crypto Folder/Library/Library.bib"))
(setq org-ref-default-bibliography '("~/pCloud Drive/Crypto Folder/Library/Library.bib")
      org-ref-pdf-directory "~/pCloud Drive/Crypto Folder/Library/")
#+END_SRC

